apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: development-ortami
  description: Development ortamındaki servisler ve veritabanları
spec:
  owner: team-dev

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-web-1
  description: Nova Web ve Nova Login (10.15.40.80)
spec:
  type: service
  lifecycle: development
  owner: team-dev
  system: development-ortami

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-web-2
  description: Nova Web ve Nova Login (10.15.40.81)
spec:
  type: service
  lifecycle: development
  owner: team-dev
  system: development-ortami

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-server-1
  description: Nova Server, Console ve Bordro Service (10.15.41.50)
spec:
  type: service
  lifecycle: development
  owner: team-dev
  system: development-ortami

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-server-2
  description: Nova Server ve Bordro Service (10.15.41.51)
spec:
  type: service
  lifecycle: development
  owner: team-dev
  system: development-ortami

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: global-db
  description: Global Database (PostgreSQL v17)
spec:
  type: database
  owner: dba-team
  system: development-ortami

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: paid-db
  description: Paid Database (PostgreSQL v17)
spec:
  type: database
  owner: dba-team
  system: development-ortami

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: e-defter-db
  description: E-Defter Database
spec:
  type: database
  owner: dba-team
  system: development-ortami
