# Nova Sistemi
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: nova-system
  title: Nova Team Sistemi
  description: Nova Team Sistemi
spec:
  owner: nova-team

---

# Development Ortamı
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: development-ortami
  title: Development Ortamı
  description: Development Ortamı
spec:
  type: environment
  lifecycle: development
  owner: nova-team
  system: nova-system

---

# 10.15.40.80 Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 10.15.40.80
  title: 10.15.40.80
  description: Nova.Web ve Nova.Login
spec:
  type: service
  lifecycle: development
  owner: nova-team
  subcomponentOf: development-ortami

---

# Nova.Web (10.15.40.80) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-web-10.15.40.80
  title: Nova Web
  description: Nova.Web
  links:
    - title: Nova.Web
      url: https://www-dev.zirvenova.net
spec:
  type: service
  lifecycle: development
  owner: nova-team
  subcomponentOf: 10.15.40.80

---

# Nova.Login (10.15.40.80) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-login-10.15.40.80
  title: Nova Login
  description: Nova.Login
  links:
    - title: Nova.Login
      url: https://login-dev.zirvenova.net
spec:
  type: service
  lifecycle: development
  owner: nova-team
  subcomponentOf: 10.15.40.80

---

# 10.15.40.81 Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 10.15.40.81
  title: 10.15.40.81
  description: Nova.Web ve Nova.Login
spec:
  type: service
  lifecycle: development
  owner: nova-team
  subcomponentOf: development-ortami
  
---

# Nova.Web (10.15.40.81) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-web-10.15.40.81
  title: Nova Web
  description: Nova.Web
  links:
    - title: Nova.Web
      url: https://www-dev.zirvenova.net
spec:
  type: service
  lifecycle: development
  owner: nova-team
  subcomponentOf: 10.15.40.81

---

# Nova.Login (10.15.40.81) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-login-10.15.40.81
  title: Nova Login
  description: Nova.Login
  links:
    - title: Nova.Login
      url: https://login-dev.zirvenova.net
spec:
  type: service
  lifecycle: development
  owner: nova-team
  subcomponentOf: 10.15.40.81

---

# 10.15.41.50 Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 10.15.41.50
  title: 10.15.41.50
  description: Nova.Server, Nova.Console ve Nova.BordroService
spec:
  type: service
  lifecycle: development
  owner: nova-team
  subcomponentOf: development-ortami
  
---

# Nova Server (10.15.41.50) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-server-10.15.41.50
  title: Nova Server
  description: Nova.Server
  links:
    - title: Nova.Server
      url: https://server-dev.zirvenova.net
spec:
  type: server
  lifecycle: development
  owner: nova-team
  subcomponentOf: 10.15.41.50
  dependsOn:
    - resource:global-database
    - resource:paid-database
    - resource:e-defter-db
    - resource:redis-cache

---

# Nova Server (10.15.41.51) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-server-10.15.41.51
  title: Nova Server
  description: Nova.Server
  links:
    - title: Nova.Server
      url: https://server-dev.zirvenova.net
spec:
  type: server
  lifecycle: development
  owner: nova-team
  subcomponentOf: 10.15.41.51
  dependsOn:
    - resource:global-database
    - resource:paid-database
    - resource:e-defter-db

---

# Nova Console Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-console
  title: Nova Console
  description: Nova.Console
  tags: 
    - cli-app
spec:
  type: console
  lifecycle: development
  owner: nova-team
  subcomponentOf: 10.15.41.50

---

# Nova Bordro Service (10.15.41.50) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-bordro-service-10.15.41.50
  title: Nova Bordro Service
  description: Nova.BordroService
  links:
    - title: Nova.BordroService
      url: http://localhost:5052
spec:
  type: service
  lifecycle: development
  owner: nova-team
  subcomponentOf: 10.15.41.50

---

# Nova Bordro Service (10.15.41.51) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-bordro-service-10.15.41.51
  title: Nova Bordro Service
  description: Nova.BordroService
  links:
    - title: Nova.BordroService
      url: http://localhost:5052
spec:
  type: service
  lifecycle: development
  owner: nova-team
  subcomponentOf: 10.15.41.51

---

# 10.15.41.51 Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 10.15.41.51
  title: 10.15.41.51
  description: Nova.Server ve Nova.BordroService
spec:
  type: service
  lifecycle: development
  owner: nova-team
  subcomponentOf: development-ortami

---

# Global Database
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: global-database
  title: Global Database
  description: PostgreSQL v17 Global Database (10.15.42.91)
  tags:
    - postgresql
    - version-17
spec:
  type: database
  owner: nova-team
  data:
    host: 10.15.42.91
    engine: postgresql
    version: 17

---

# Paid Database
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: paid-database
  title: Paid Database
  description: PostgreSQL v17 Paid Database (10.15.42.92)
  tags:
    - postgresql
    - version-17
spec:
  type: database
  owner: nova-team
  data:
    host: 10.15.42.92
    engine: postgresql
    version: 17

---

# E-Defter Database
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: e-defter-db
  title: E-Defter DB
  description: E-Defter DB (10.15.42.86)
  tags:
    - postgresql
    - glzednovapsql01
spec:
  type: database
  owner: nova-team
  data:
    host: 10.15.42.86
    engine: postgresql
    instance: GLZEDNOVAPSQL01

---

# Redis Cache
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: redis-cache
  title: Redis Cache
  description: Redis Cache (10.15.41.38:6379)
  tags:
    - redis      
spec:
  type: cache
  owner: nova-team
  data:
    host: 10.15.41.38
    port: 6379
    engine: redis

---

# YENİ ORTAM

# Production Ortamı
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: production-ortami
  title: Production Ortamı
  description: Production Ortamı
spec:
  type: environment
  lifecycle: production
  owner: nova-team
  system: nova-system

---

# 172.18.40.80 Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 172.18.40.80
  title: 172.18.40.80
  description: Nova.Web ve Nova.Login
spec:
  type: service
  lifecycle: production
  owner: nova-team
  subcomponentOf: production-ortami

---

# Nova.Web (172.18.40.80) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-web-172.18.40.80
  title: Nova Web
  description: Nova.Web
  links:
    - title: Nova.Web
      url: https://www-dev.zirvenova.net
spec:
  type: service
  lifecycle: production
  owner: nova-team
  subcomponentOf: 172.18.40.80

---

# Nova.Login (172.18.40.80) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-login-172.18.40.80
  title: Nova Login
  description: Nova.Login
  links:
    - title: Nova.Login
      url: https://login-dev.zirvenova.net
spec:
  type: service
  lifecycle: production
  owner: nova-team
  subcomponentOf: 172.18.40.80

---

# 172.18.40.81 Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 172.18.40.81
  title: 172.18.40.81
  description: Nova.Web ve Nova.Login
spec:
  type: service
  lifecycle: production
  owner: nova-team
  subcomponentOf: production-ortami

---

# Nova.Web (172.18.40.81) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-web-172.18.40.81
  title: Nova Web
  description: Nova.Web
  links:
    - title: Nova.Web
      url: https://www-dev.zirvenova.net
spec:
  type: service
  lifecycle: production
  owner: nova-team
  subcomponentOf: 172.18.40.81

---

# Nova.Login (172.18.40.81) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-login-172.18.40.81
  title: Nova Login
  description: Nova.Login
  links:
    - title: Nova.Login
      url: https://login-dev.zirvenova.net
spec:
  type: service
  lifecycle: production
  owner: nova-team
  subcomponentOf: 172.18.40.81

---

# 172.18.41.50 Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 172.18.41.50
  title: 172.18.41.50
  description: Nova.Server, Nova.Console ve Nova.BordroService
spec:
  type: service
  lifecycle: production
  owner: nova-team
  subcomponentOf: production-ortami

---

# Nova Server (172.18.41.50) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-server-172.18.41.50
  title: Nova Server
  description: Nova.Server
  links:
    - title: Nova.Server
      url: https://server-dev.zirvenova.net
spec:
  type: server
  lifecycle: production
  owner: nova-team
  subcomponentOf: 172.18.41.50
  dependsOn:
    - resource:global-database-172.18.42.80
    - resource:paid-database-172.18.42.81
    - resource:paid-database-172.18.42.82
    - resource:paid-database-172.18.42.83
    - resource:paid-database-172.18.42.84
    - resource:paid-database-172.18.42.85
    - resource:e-defter-db-172.18.42.86

---

# Nova Console (172.18.41.50) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-console-172.18.41.50
  title: Nova Console
  description: Nova.Console
  tags: 
    - cli-app
spec:
  type: console
  lifecycle: production
  owner: nova-team
  subcomponentOf: 172.18.41.50

---

# Nova Bordro Service (172.18.41.50) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-bordro-service-172.18.41.50
  title: Nova Bordro Service
  description: Nova.BordroService
  links:
    - title: Nova.BordroService
      url: http://localhost:5052
spec:
  type: service
  lifecycle: production
  owner: nova-team
  subcomponentOf: 172.18.41.50

---

# 172.18.41.51 Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 172.18.41.51
  title: 172.18.41.51
  description: Nova.Server ve Nova.BordroService
spec:
  type: service
  lifecycle: production
  owner: nova-team
  subcomponentOf: production-ortami

---

# Nova Server (172.18.41.51) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-server-172.18.41.51
  title: Nova Server
  description: Nova.Server
  links:
    - title: Nova.Server
      url: https://server-dev.zirvenova.net
spec:
  type: server
  lifecycle: production
  owner: nova-team
  subcomponentOf: 172.18.41.51
  dependsOn:
    - resource:global-database-172.18.42.80
    - resource:paid-database-172.18.42.81
    - resource:paid-database-172.18.42.82
    - resource:paid-database-172.18.42.83
    - resource:paid-database-172.18.42.84
    - resource:paid-database-172.18.42.85
    - resource:e-defter-db-172.18.42.86

---

# Nova Bordro Service (172.18.41.51) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-bordro-service-172.18.41.51
  title: Nova Bordro Service
  description: Nova.BordroService
  links:
    - title: Nova.BordroService
      url: http://localhost:5052
spec:
  type: service
  lifecycle: production
  owner: nova-team
  subcomponentOf: 172.18.41.51

---

# 172.18.41.52 Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 172.18.41.52
  title: 172.18.41.52
  description: Nova.Server ve Nova.BordroService
spec:
  type: service
  lifecycle: production
  owner: nova-team
  subcomponentOf: production-ortami

---

# Nova Server (172.18.41.52) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-server-172.18.41.52
  title: Nova Server
  description: Nova.Server
  links:
    - title: Nova.Server
      url: https://server-dev.zirvenova.net
spec:
  type: server
  lifecycle: production
  owner: nova-team
  subcomponentOf: 172.18.41.52
  dependsOn:
    - resource:global-database-172.18.42.80
    - resource:paid-database-172.18.42.81
    - resource:paid-database-172.18.42.82
    - resource:paid-database-172.18.42.83
    - resource:paid-database-172.18.42.84
    - resource:paid-database-172.18.42.85
    - resource:e-defter-db-172.18.42.86

---

# Nova Bordro Service (172.18.41.52) Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-bordro-service-172.18.41.52
  title: Nova Bordro Service
  description: Nova.BordroService
  links:
    - title: Nova.BordroService
      url: http://localhost:5052
spec:
  type: service
  lifecycle: production
  owner: nova-team
  subcomponentOf: 172.18.41.52

---

# Global Database (172.18.42.80)
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: global-database-172.18.42.80
  title: Global Database
  description: glznovagpsql01.atrosdc.com
  tags:
    - postgresql
    - version-17
spec:
  type: database
  owner: nova-team
  data:
    host: 172.18.42.80
    engine: postgresql
    version: 17

---

# Paid Database (172.18.42.81)
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: paid-database-172.18.42.81
  title: Paid Database
  description: glznovagpsql01.atrosdc.com
  tags:
    - postgresql
    - version-17
spec:
  type: database
  owner: nova-team
  data:
    host: 172.18.42.81
    engine: postgresql
    version: 17

---

# Paid Database (172.18.42.82)
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: paid-database-172.18.42.82
  title: Paid Database
  description: glznovagpsql02.atrosdc.com
  tags:
    - postgresql
    - version-17
spec:
  type: database
  owner: nova-team
  data:
    host: 172.18.42.82
    engine: postgresql
    version: 17

---

# Paid Database (172.18.42.83)
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: paid-database-172.18.42.83
  title: Paid Database
  description: glznovagpsql03.atrosdc.com
  tags:
    - postgresql
    - version-17
spec:
  type: database
  owner: nova-team
  data:
    host: 172.18.42.83
    engine: postgresql
    version: 17

---

# Paid Database (172.18.42.84)
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: paid-database-172.18.42.84
  title: Paid Database
  description: glznovagpsql04.atrosdc.com
  tags:
    - postgresql
    - version-17
spec:
  type: database
  owner: nova-team
  data:
    host: 172.18.42.84
    engine: postgresql
    version: 17

---

# Paid Database (172.18.42.85)
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: paid-database-172.18.42.85
  title: Paid Database
  description: glznovagpsql05.atrosdc.com
  tags:
    - postgresql
    - version-17
spec:
  type: database
  owner: nova-team
  data:
    host: 172.18.42.85
    engine: postgresql
    version: 17

---

# E-Defter Database (172.18.42.86)
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: e-defter-db-172.18.42.86
  title: E-Defter DB
  description: E-Defter DB (172.18.42.86)
  tags:
    - postgresql
    - glzednovapsql01
spec:
  type: database
  owner: nova-team
  data:
    host: 10.15.42.86
    engine: postgresql
    instance: GLZEDNOVAPSQL01
