apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: development-ortami
  title: Development Ortamı
  description: Development ortamındaki tüm sunucular, servisler ve veritabanları
spec:
  owner: team-dev

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-web-1
  title: Nova Web 1
  description: |
    IP: 10.15.40.80
    Servisler:
      - Nova.Web: https://www-dev.zirvenova.net
      - Nova.Login: https://login-dev.zirvenova.net
spec:
  type: service
  lifecycle: development
  owner: team-dev
  system: development-ortami

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-web-2
  title: Nova Web 2
  description: |
    IP: 10.15.40.81
    Servisler:
      - Nova.Web: https://www-dev.zirvenova.net
      - Nova.Login: https://login-dev.zirvenova.net
spec:
  type: service
  lifecycle: development
  owner: team-dev
  system: development-ortami

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-server-1
  title: Nova Server 1
  description: |
    IP: 10.15.41.50
    Servisler:
      - Nova.Server: https://server-dev.zirvenova.net
      - Nova.BordroService: http://localhost:5052
      - Nova.Console: cli app
      - Redis: 10.15.41.38:6379
spec:
  type: service
  lifecycle: development
  owner: team-dev
  system: development-ortami

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nova-server-2
  title: Nova Server 2
  description: |
    IP: 10.15.41.51
    Servisler:
      - Nova.Server: https://server-dev.zirvenova.net
      - Nova.BordroService: http://localhost:5052
spec:
  type: service
  lifecycle: development
  owner: team-dev
  system: development-ortami

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: global-db
  title: Global Database
  description: |
    IP: 10.15.42.91 - PostgreSQL v17
spec:
  type: database
  owner: dba-team
  system: development-ortami

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: paid-db
  title: Paid Database
  description: |
    IP: 10.15.42.92 - PostgreSQL v17
spec:
  type: database
  owner: dba-team
  system: development-ortami

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: e-defter-db
  title: E-Defter DB
  description: |
    IP: 10.15.42.86 - GLZEDNOVAPSQL01
spec:
  type: database
  owner: dba-team
  system: development-ortami
