apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: development
  title: Development
  description: Development Ortam覺'n覺 kapsayan sistem
spec:
  owner: dev-team

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: development-ortami
  title: Development Ortam覺
  description: Development Ortam覺
spec:
  type: environment
  lifecycle: development
  owner: dev-team
  system: development

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 10.15.40.80
  title: 10.15.40.80
  description: Nova.Web ve Nova.Login
  links:
    - title: Nova.Web
      url: https://www-dev.zirvenova.net
    - title: Nova.Login
      url: https://login-dev.zirvenova.net
spec:
  type: service
  lifecycle: development
  owner: dev-team
  subcomponentOf: development-ortami
  dependsOn:
    - resource:global-database
    - resource:paid-database
    - resource:e-defter-db

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 10.15.40.81
  title: 10.15.40.81
  description: Nova.Web ve Nova.Login
  links:
    - title: Nova.Web
      url: https://www-dev.zirvenova.net
    - title: Nova.Login
      url: https://login-dev.zirvenova.net
spec:
  type: service
  lifecycle: development
  owner: dev-team
  subcomponentOf: development-ortami
  dependsOn:
    - resource:global-database
    - resource:paid-database
    - resource:e-defter-db
  
---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 10.15.41.50
  title: 10.15.41.50
  description: Nova.Server, Nova.Console ve Nova.BordroService
  links:
    - title: Nova.Server
      url: https://server-dev.zirvenova.net
    - title: Nova.Console
      url: cli://nova.console
    - title: Nova.BordroService
      url: http://localhost:5052
    - title: Redis
      url: redis://10.15.41.38:6379
spec:
  type: service
  lifecycle: development
  owner: dev-team
  subcomponentOf: development-ortami
  dependsOn:
    - resource:global-database
    - resource:paid-database
    - resource:e-defter-db
    - resource:redis-cache
  
---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 10.15.41.51
  title: 10.15.41.51
  description: Nova.Server ve Nova.BordroService
  links:
    - title: Nova.Server
      url: https://server-dev.zirvenova.net
    - title: Nova.BordroService
      url: http://localhost:5052
spec:
  type: service
  lifecycle: development
  owner: dev-team
  subcomponentOf: development-ortami
  dependsOn:
    - resource:global-database
    - resource:paid-database
    - resource:e-defter-db

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: global-database
  title: Global Database
  description: PostgreSQL v17 Global Database
  annotations:
    db/host: 10.15.42.91
    db/engine: postgresql
    db/version: "17"
spec:
  type: database
  owner: dev-team
  data:
    host: 10.15.42.91
    engine: postgresql
    version: 17

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: paid-database
  title: Paid Database
  description: PostgreSQL v17 Paid Database
  annotations:
    db/host: 10.15.42.92
    db/engine: postgresql
    db/version: "17"
spec:
  type: database
  owner: dev-team
  data:
    host: 10.15.42.92
    engine: postgresql
    version: 17

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: e-defter-db
  title: E-Defter DB
  description: E-Defter DB
  annotations:
    db/host: 10.15.42.86
    db/engine: postgresql
    db/instance: GLZEDNOVAPSQL01
spec:
  type: database
  owner: dev-team
  data:
    host: 10.15.42.86
    engine: postgresql
    instance: GLZEDNOVAPSQL01

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: redis-cache
  title: Redis Cache
  description: Redis Cache
  annotations:
    cache/host: 10.15.41.38
    cache/port: 6379
    cache/engine: redis    
spec:
  type: cache
  owner: dev-team
  data:
    host: 10.15.41.38
    port: 6379
    engine: redis
